
package chungtoi.integration.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChungToiWSServer", targetNamespace = "http://ws.integration.chungtoi/", wsdlLocation = "http://localhost:8084/chungtoi/ChungToiWSServer?wsdl")
public class ChungToiWSServer_Service
    extends Service
{

    private final static URL CHUNGTOIWSSERVER_WSDL_LOCATION;
    private final static WebServiceException CHUNGTOIWSSERVER_EXCEPTION;
    private final static QName CHUNGTOIWSSERVER_QNAME = new QName("http://ws.integration.chungtoi/", "ChungToiWSServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/chungtoi/ChungToiWSServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHUNGTOIWSSERVER_WSDL_LOCATION = url;
        CHUNGTOIWSSERVER_EXCEPTION = e;
    }

    public ChungToiWSServer_Service() {
        super(__getWsdlLocation(), CHUNGTOIWSSERVER_QNAME);
    }

    public ChungToiWSServer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHUNGTOIWSSERVER_QNAME, features);
    }

    public ChungToiWSServer_Service(URL wsdlLocation) {
        super(wsdlLocation, CHUNGTOIWSSERVER_QNAME);
    }

    public ChungToiWSServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHUNGTOIWSSERVER_QNAME, features);
    }

    public ChungToiWSServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChungToiWSServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChungToiWSServer
     */
    @WebEndpoint(name = "ChungToiWSServerPort")
    public ChungToiWSServer getChungToiWSServerPort() {
        return super.getPort(new QName("http://ws.integration.chungtoi/", "ChungToiWSServerPort"), ChungToiWSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChungToiWSServer
     */
    @WebEndpoint(name = "ChungToiWSServerPort")
    public ChungToiWSServer getChungToiWSServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.integration.chungtoi/", "ChungToiWSServerPort"), ChungToiWSServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHUNGTOIWSSERVER_EXCEPTION!= null) {
            throw CHUNGTOIWSSERVER_EXCEPTION;
        }
        return CHUNGTOIWSSERVER_WSDL_LOCATION;
    }

}
