
package chungtoi.integration.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChungToiWSServer", targetNamespace = "http://ws.integration.chungtoi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChungToiWSServer {


    /**
     * 
     * @param player1Name
     * @param player1Id
     * @param player2Name
     * @param player2Id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preRegister", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.PreRegister")
    @ResponseWrapper(localName = "preRegisterResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.PreRegisterResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/preRegisterRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/preRegisterResponse")
    public int preRegister(
        @WebParam(name = "player1Name", targetNamespace = "")
        String player1Name,
        @WebParam(name = "player1Id", targetNamespace = "")
        int player1Id,
        @WebParam(name = "player2Name", targetNamespace = "")
        String player2Name,
        @WebParam(name = "player2Id", targetNamespace = "")
        int player2Id);

    /**
     * 
     * @param playerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOppositePlayer", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.GetOppositePlayer")
    @ResponseWrapper(localName = "getOppositePlayerResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.GetOppositePlayerResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/getOppositePlayerRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/getOppositePlayerResponse")
    public String getOppositePlayer(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId);

    /**
     * 
     * @param playerId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isMyTurn", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.IsMyTurn")
    @ResponseWrapper(localName = "isMyTurnResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.IsMyTurnResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/isMyTurnRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/isMyTurnResponse")
    public int isMyTurn(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId);

    /**
     * 
     * @param orientation
     * @param movementDirection
     * @param stepSize
     * @param actualPosition
     * @param playerId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "movePiece", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.MovePiece")
    @ResponseWrapper(localName = "movePieceResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.MovePieceResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/movePieceRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/movePieceResponse")
    public int movePiece(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId,
        @WebParam(name = "actualPosition", targetNamespace = "")
        int actualPosition,
        @WebParam(name = "movementDirection", targetNamespace = "")
        int movementDirection,
        @WebParam(name = "stepSize", targetNamespace = "")
        int stepSize,
        @WebParam(name = "orientation", targetNamespace = "")
        int orientation);

    /**
     * 
     * @param playerId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasGame", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.HasGame")
    @ResponseWrapper(localName = "hasGameResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.HasGameResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/hasGameRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/hasGameResponse")
    public int hasGame(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId);

    /**
     * 
     * @param playerId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "endGame", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.EndGame")
    @ResponseWrapper(localName = "endGameResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.EndGameResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/endGameRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/endGameResponse")
    public int endGame(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId);

    /**
     * 
     * @param playerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameStatus", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.GetGameStatus")
    @ResponseWrapper(localName = "getGameStatusResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.GetGameStatusResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/getGameStatusRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/getGameStatusResponse")
    public String getGameStatus(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId);

    /**
     * 
     * @param orientation
     * @param position
     * @param playerId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPiece", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.InsertPiece")
    @ResponseWrapper(localName = "insertPieceResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.InsertPieceResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/insertPieceRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/insertPieceResponse")
    public int insertPiece(
        @WebParam(name = "playerId", targetNamespace = "")
        int playerId,
        @WebParam(name = "position", targetNamespace = "")
        int position,
        @WebParam(name = "orientation", targetNamespace = "")
        int orientation);

    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPlayer", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.CreatePlayer")
    @ResponseWrapper(localName = "createPlayerResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.CreatePlayerResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/createPlayerRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/createPlayerResponse")
    public int createPlayer(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.integration.chungtoi/", className = "chungtoi.integration.ws.client.HelloResponse")
    @Action(input = "http://ws.integration.chungtoi/ChungToiWSServer/helloRequest", output = "http://ws.integration.chungtoi/ChungToiWSServer/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
